### PR TITLE
Updated to last Micropython version (1.12.889), use newest csdk and other changes

### PR DESCRIPTION
**Pull request by arlucio**
Up to date with Micropython main repository (some files remain different)
Now using the new version of GPRS-C-SDK-LIB (2131) and not doing patchs anymore
Added uasyncio module
Deleted st7735 and blink module

### CODE REVIEW

**Comment by pulkin** [comment]
So, the newer SDK is free of APN and other issues? Or it is just that we need to patch that as well?

**Comment by arlucio** [comment]
Seems like it's free of these issues, I'm able to connect GPRS normally, use sockets and get sockets errors. Doing everything I was doing before but now without applying the patchs. Would be great if you could check and see if everything is also working for you.

**Comment by arlucio** [comment]
Btw, I've deleted the st7735 module, but I believe would be nice to keep hw libs relative to this port in some other folder.

**Comment by pulkin** [comment]
There is a little bit too much for this PR. I updated master by removing `st7735` and updating the binary blob and accompanying submodules. Unfortunately, I hard pushed GPRS_C_SDK so nobody will be able to build a range of commits prior to this point :(.

2129 bugs are still there: you likely forgot to flash the bigger lod to observe them.

**Comment by arlucio** [comment]
So, seems like the patches are still necessary, right? As you updated the file with new addresses. 
I don't really know much about that or the issues, I just tested my code without the patch and it worked.

So, I gonna close this, I think would be better for me to open some specific PRs, right? Or if you want to make the changes, there is not much, just some changes that are necessary to be able to push the upstream version and build the firmware successfully. Also, some changes I made were not really ideal, like reverting changes in py/stream.c file from upstream, maybe you have a better solution to that.

Right now I'm working on implementing interruptions on machine_pin, hope to be able to make a PR for that soon.

**Comment by pulkin** [comment]
I think I will be able to merge this. Interrupts sound interesting, good luck with that!

**Pull request merged**
