### PR TITLE
Add optional timeout arguments to `cellular` and `gps` functions

### PR DESCRIPTION
**Pull request by bokolob**

### CODE REVIEW

**Comment by pulkin** [comment]
I see some valuable additions, thank you. I'll need more time to merge everything. Btw, there is an abandoned `sms_from_raw` which might be of your interest.

**Comment by bokolob** [comment]
My fix for SMS.list() is broken 8(

**Comment by bokolob** [comment]
By now everything is ok :)

**Comment by pulkin** [comment]
I added `cellular.SMS(timeout)` and `cellular.SMS.get_storage_size()` based on what is here. I also added the atomic section macro but I am wondering if there is any practical matter why you defined it?

I did not touch the rest yet. It would be much better if you make small PRs addressing specific points.

**Comment by bokolob** [comment]
I’m planning to add interrups support, and then e.g. schedule method might be called inside himself. By now I can’t say for sure, but it makes code seem more reliable for different kind of usages.

**Pull request closed without merging**
